#pragma once

typedef enum TEMPLATE_CODE{
    INIT_IDENTIFIER_WITHOUT_VALUE,
    INIT_IDENTIFIER_WITH_VALUE,
    INIT_IDENTIFIER_WITH_IDENTIFIER,
    INIT_IDENTIFIER_WITH_EXPRESSTION
}TEMPLATE_CODE;

typedef struct Template{
    TEMPLATE_CODE templateCode;
}Template;